services:
  app:
    image: custom-app:1.0
    environment:
      DB_USER: myuser
      DB_PWD: mypassword
      DB_SERVER: mysql
      DB_NAME: mydb
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 15s
      retries: 10
      start_period: 10s

  
  
